/**
 * This code was generated by Builder.io.
 */

export default function Hero() {
  return (
    <section className="w-full self-stretch pl-4 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:items-stretch max-md:gap-0">
        <div className="flex w-3/5 flex-col items-stretch max-md:ml-0 max-md:w-full">
          <div className="my-auto flex flex-col items-start max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-col items-start self-stretch max-md:max-w-full">
              <h1 className="text-6xl font-extrabold leading-[75px] text-white max-md:max-w-full max-md:text-4xl">
                APRENDÉ A CULTIVAR CON TODA LA CREW
              </h1>
              <p className="mt-6 text-xl leading-8 text-gray-400 max-md:max-w-full">
                El tipo de cultivo en el hemisferio sur del planeta se trata de muchas maneras diferentes, aprende con
                nosotros y compartí tus experiencias!
              </p>
            </div>
            <div className="mt-10 self-stretch max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div className="flex w-6/12 flex-col items-stretch max-md:ml-0 max-md:w-full">
                  <div className="flex grow flex-col items-start max-md:mt-10">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/ddb956d2-b561-48ed-a0a9-a71f7c924dc7?apiKey=c206d410c40d4fe9884874cce4378f6a&"
                      className="aspect-square w-8 max-w-full self-start overflow-hidden object-cover object-center"
                      alt="Event Image"
                    />
                    <div className="mt-4 flex w-[366px] max-w-full flex-col items-start self-start">
                      <div className="self-start whitespace-nowrap text-xl font-semibold leading-8 text-white">
                        28 November 2021
                      </div>
                      <div className="mt-1.5 text-base leading-6 text-gray-400">
                        Join us at FlowBite 2021 to understand what’s next as the global tech and startup ecosystem
                        reimagines, rebuilds, and rethinks the future of everything.
                      </div>
                    </div>
                    <div className="mt-4 flex w-[139px] max-w-full items-start justify-center gap-2 self-start rounded-lg bg-blue-600 py-2.5 pl-5 pr-5">
                      <div className="self-stretch text-sm font-medium leading-5 text-white">
                        <a href="#" className="self-stretch text-sm font-medium leading-5 text-white">
                          Conference
                        </a>
                      </div>
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e802e71a-6d6a-43c5-bd28-8d2ea1633d15?apiKey=c206d410c40d4fe9884874cce4378f6a&"
                        className="aspect-square w-5 max-w-full self-stretch overflow-hidden object-cover object-center"
                        alt="Conference Icon"
                      />
                    </div>
                  </div>
                </div>
                <div className="ml-5 flex w-6/12 flex-col items-stretch max-md:ml-0 max-md:w-full">
                  <div className="flex grow flex-col items-start max-md:mt-10">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/5bf1dfbc-9925-4fea-b8e8-2fa72b2b0113?apiKey=c206d410c40d4fe9884874cce4378f6a&"
                      className="aspect-square w-8 max-w-full self-start overflow-hidden object-cover object-center"
                      alt="Speaker Image"
                    />
                    <div className="mt-4 flex w-[366px] max-w-full flex-col items-start self-start">
                      <div className="self-start whitespace-nowrap text-xl font-semibold leading-8 text-white">
                        25+ top notch speakers
                      </div>
                      <div className="mt-1.5 text-base leading-6 text-gray-400">
                        Here you will find keynote speakers, who all are able to talk about Recruiting. Click on the
                        individual keynote speakers and read more about them and their keynotes.
                      </div>
                    </div>
                    <div className="mt-4 flex w-[120px] max-w-full items-start justify-center gap-2 self-start rounded-lg border border-solid border-[color:var(--white,#FFF)] py-2.5 pl-5 pr-5">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b14d3ba7-d019-488e-8c52-7f4ae3aaa421?apiKey=c206d410c40d4fe9884874cce4378f6a&"
                        className="aspect-square w-5 max-w-full self-stretch overflow-hidden object-cover object-center"
                        alt="View List Icon"
                      />
                      <div className="self-stretch whitespace-nowrap text-sm font-medium leading-5 text-white">
                        <a href="#" className="self-stretch text-sm font-medium leading-5 text-white">
                          View list
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="ml-5 flex w-2/5 flex-col items-stretch max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            srcSet="..."
            className="aspect-[0.77] w-full grow overflow-hidden object-cover object-center max-md:mt-10 max-md:max-w-full"
            alt="Secondary Image"
          />
        </div>
      </div>
    </section>
  )
}
